[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Single redirect rule for SSR - this is the standard Astro SSR setup
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/entry"
  status = 200