[build]
  command = "npm run build"
  publish = "dist/client"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/ssr"
  status = 200