[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# For Netlify adapter, redirect to the entry function
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/entry"
  status = 200