[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Handle static files first
[[redirects]]
  from = "/_astro/*"
  to = "/_astro/:splat"
  status = 200

# Handle static assets
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

# Handle all other routes with SSR
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/entry"
  status = 200