[build]
  command = "npm run build"
  publish = "dist/client"

[build.environment]
  NODE_VERSION = "18"

# For Node adapter, we need to redirect to the server function
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/ssr"
  status = 200